import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { Plus, Minus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageIntro } from '@/components/portfolio-shell';
import { pageHead } from '@/lib/portfolio';
export const Route = createFileRoute('/experience')({ head: () => pageHead('Professional Experience', 'Gauri’s work at Publicis Sapient, Lenek Technologies and Care Cadet — building AI systems from models to production.'), component: ExperiencePage });
const groups = [{title:'AI Systems & ML Engineering',items:['Traditional ML & GenAI pipelines','Workflow orchestration with Kubeflow / Ray / MLflow','RAG systems over 10K+ knowledge bases','GPU-accelerated multimodal model experimentation']},{title:'AI Observability & Evaluation',items:['Application-wide LLM observability across 25+ distributed APIs','RAG & agent tracing with Langfuse / LLM Gateway','Automated evaluation and LLM-as-a-Judge','Load, performance and quality monitoring']},{title:'Agentic & Async AI Applications',items:['Multi-agent LangGraph workflows','Conversational storyboard generation','Asynchronous multimodal generation using Celery','Scalable backend, frontend and infrastructure','Kubernetes scaling and CI/CD']}];
function ExperiencePage() { const [expanded,setExpanded] = useState<number[]>([0]); return <main className="page-wrap page-enter"><PageIntro label="The journey so far" title="Professional Experience" description="Building AI systems from models to production."/><div className="timeline"><section className="timeline-item"><p className="font-mono text-[10px] text-primary mb-3">2024 — PRESENT</p><h2>Publicis Sapient</h2><p className="timeline-meta">Senior Associate Data Scientist L1 · Jul 2024–Present · Bengaluru</p>{groups.map((group,i) => <div key={group.title} className="experience-detail"><Button variant="ghost" className="experience-toggle" aria-expanded={expanded.includes(i)} aria-controls={`experience-${i}`} onClick={() => setExpanded(prev => prev.includes(i) ? prev.filter(n => n!==i) : [...prev,i])}><span className="flex gap-4"><span className="text-primary font-mono text-xs pt-1">0{i+1}</span>{group.title}</span>{expanded.includes(i) ? <Minus /> : <Plus />}</Button>{expanded.includes(i) && <ul id={`experience-${i}`} className="experience-list">{group.items.map(item => <li key={item}>{item}</li>)}</ul>}</div>)}<div className="impact-strip">{[['10K+','Knowledge bases'],['25+','Distributed APIs'],['15+','Product flows'],['100+','Defects resolved'],['30%','Throughput improvement']].map(([value,label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></section><section className="timeline-item"><p className="font-mono text-[10px] text-primary mb-3">2023 — 2024</p><h2>Care Cadet</h2><p className="timeline-meta">Big Data Analyst · Sep 2023–Jan 2024</p><p className="text-sm text-muted-foreground leading-loose">15M+ insurance records · PySpark · MongoDB · Healthcare Recommendation Systems · Clinical Decision Support</p></section><section className="timeline-item"><p className="font-mono text-[10px] text-primary mb-3">2023</p><h2>Lenek Technologies</h2><p className="timeline-meta">Computer Vision Intern · Jan 2023–Sep 2023</p><p className="text-sm text-muted-foreground leading-loose">500K+ chest X-rays · CNNs · Domain Adaptation · Automated EDA · +15% model accuracy</p></section></div></main>; }
