import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowRight, ArrowUpRight, Workflow, ScanEye, Bug } from 'lucide-react';
import { PageIntro } from '@/components/portfolio-shell';
import { pageHead } from '@/lib/portfolio';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
export const Route = createFileRoute('/projects')({ head: () => pageHead("Things I've Built", 'Explore Gauri’s AI workflow orchestration, agentic defect analysis and generative microscopy projects.'), component: ProjectsPage });
const projects = [{title:'AI Workflow Orchestration',category:'AI Systems · Distributed Systems · MLOps',description:'Designing reliable orchestration for complex AI workflows with async execution, parallelism, retries, observability and production reliability.',tech:['Python','Ray','Kubeflow','Kubernetes','Celery','GCP'],flow:['AI workflows','Async workers','Production'],icon:Workflow,detail:['Asynchronous execution and parallel processing','Retries and reliable workflow orchestration','Observability and production infrastructure']},{title:'AI-Powered Defect Analyzer',category:'Agentic AI · Developer Productivity',description:'An automated system that analyzes application defects, gathers context, identifies likely root causes and assists engineers with debugging.',tech:['Agentic AI','Context Retrieval','AI Analysis'],flow:['Defect','Context','AI analysis','Root cause'],icon:Bug,detail:['Gather context from logs, code and traces','Analyze defects and identify likely root causes','Recommend next steps for engineers']},{title:'Generative AI for High-Resolution Microscopy',category:'Research · Computer Vision · Generative AI',description:'Exploring generative models for reconstructing high-resolution microscopy images from lower-resolution observations.',tech:['GANs','VAEs','U-Net','X-Net'],flow:['Low-res input','Generative model','High-res output'],icon:ScanEye,detail:['Low-resolution microscopy observations','Generative model exploration with GANs and VAEs','High-resolution reconstruction with U-Net and X-Net']}];
function ProjectsPage() { const [selected,setSelected] = useState<typeof projects[number] | null>(null); return <main className="page-wrap page-enter"><section className="section-band"><h2 className="section-heading -rotate-1"><strong>CURRENTLY</strong> BUILDING</h2><div className="building-grid">{[{title:'Personalized Newspaper',category:'AI · RAG · Information Retrieval',description:'An automated personalized newspaper that curates and organizes information around user-selected topics.'},{title:'FDE Support Engine',category:'Agentic AI · System Design · Developer Tools',description:'An AI system that takes a customer problem and scale requirements and generates an end-to-end system architecture and implementation plan.'}].map(project => <article key={project.title} className="building-card"><span className="text-[10px] font-mono bg-secondary border border-primary px-2 py-1">IN PROGRESS</span><h3>{project.title}</h3><p className="font-mono text-[10px]! mb-4">{project.category}</p><p>{project.description}</p></article>)}</div></section><PageIntro label="Ideas, engineered" title="Things I've Built" description="AI systems, engineering experiments and products — from production infrastructure to generative microscopy."/><div className="project-grid pb-14">{projects.map((project,i) => <article className="project-card" key={project.title}><div className="project-visual"><div className="w-full"><project.icon className="mx-auto mb-6 text-primary" size={36} strokeWidth={1.3}/><div className="flow-diagram">{project.flow.map((node,index) => <div key={node} className="contents"><span className="flow-node">{node}</span>{index < project.flow.length-1 && <ArrowRight className="text-primary" size={15}/>}</div>)}</div></div></div><div className="project-body"><p className="font-mono text-[10px] uppercase text-primary">0{i+1} / {project.category}</p><h2>{project.title}</h2><p>{project.description}</p><div className="flex flex-wrap gap-2 mt-5 mb-5">{project.tech.map(tech => <span className="skill-pill" key={tech}>{tech}</span>)}</div><Button variant="link" className="p-0 font-mono text-xs" onClick={() => setSelected(project)}>Explore case study <ArrowUpRight /></Button></div></article>)}</div><Dialog open={!!selected} onOpenChange={open => !open && setSelected(null)}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle className="font-mono leading-relaxed">{selected?.title}</DialogTitle><DialogDescription className="leading-relaxed pt-3">{selected?.description}</DialogDescription></DialogHeader><h3 className="font-mono text-xs mt-4">SYSTEM OVERVIEW</h3><ul className="list-disc pl-5 text-sm leading-loose text-muted-foreground">{selected?.detail.map(item => <li key={item}>{item}</li>)}</ul><div className="flex flex-wrap gap-2">{selected?.tech.map(item => <span className="skill-pill" key={item}>{item}</span>)}</div></DialogContent></Dialog></main>; }
