import { Link } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowUpRight, Github, Linkedin, Mail, Menu, X, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
const links = [{ to: '/', label: 'About me' }, { to: '/projects', label: 'Projects' }, { to: '/experience', label: 'Experience' }, { to: '/resume', label: 'Resume' }, { to: '/insights', label: 'Insights' }] as const;
export function PortfolioHeader() {
  const [open, setOpen] = useState(false);
  return <><header className="page-wrap"><div className="site-header"><Link to="/" className="wordmark" aria-label="Gauri Menon home"><span>GAURI</span><span>MENON<span className="text-primary inline!">.</span></span></Link><nav className="desktop-nav flex items-center gap-8" aria-label="Main navigation">{links.map(link => <Link key={link.to} to={link.to} activeOptions={{ exact: true }} className="nav-link">{link.label}</Link>)}<Button asChild variant="outline" className="editorial-button"><Link to="/resume">Let's connect <ArrowUpRight /></Link></Button></nav><Button className="md:hidden" variant="ghost" size="icon" aria-label={open ? 'Close menu' : 'Open menu'} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</Button></div>{open && <nav aria-label="Mobile navigation" className="flex flex-col gap-1 border-b border-border py-4">{links.map(link => <Link key={link.to} to={link.to} onClick={() => setOpen(false)} className="nav-link" activeOptions={{ exact: true }}>{link.label}</Link>)}</nav>}</header></>;
}
export function SocialLinks({ resume = true }: { resume?: boolean }) {
 const [selected, setSelected] = useState<string | null>(null);
 return <><div className="social-row">{resume && <Button asChild className="editorial-button"><Link to="/resume">Resume <ArrowUpRight /></Link></Button>}{[{ label:'LinkedIn', icon:Linkedin },{ label:'GitHub', icon:Github },{ label:'Email', icon:Mail }].map(({label,icon:Icon}) => <Button key={label} variant="ghost" className="editorial-button" onClick={() => setSelected(label)}><Icon />{label}<ArrowUpRight className="size-3!" /></Button>)}</div><Dialog open={!!selected} onOpenChange={open => !open && setSelected(null)}><DialogContent><DialogHeader><DialogTitle>{selected}</DialogTitle><DialogDescription>{selected === 'Email' ? 'An email address' : `A ${selected} profile link`} hasn't been added yet.</DialogDescription></DialogHeader></DialogContent></Dialog></>;
}
export function PortfolioFooter() { return <footer className="page-wrap"><div className="site-footer"><div><Link to="/" className="font-mono text-sm font-bold">GAURI MENON.</Link><p className="mt-2">AI Engineer · AI Systems · Healthcare AI</p></div><div className="flex items-center gap-5"><Link to="/projects" className="font-mono text-xs flex items-center gap-2">Explore my work <ArrowRight size={15} /></Link><span className="font-mono text-[10px] text-muted-foreground">© {new Date().getFullYear()} Gauri Menon</span></div></div></footer>; }
export function PageIntro({ label, title, description }: { label:string; title:string; description:string }) { return <div className="page-intro"><p className="eyebrow">{label}</p><h1 className="page-title">{title}</h1><p className="page-description">{description}</p></div>; }
